### ISSUE TITLE
AttributeError: module 'sys' has no attribute '_MEIPASS'

### ISSUE THREAD

**Issue by xevilstar** [blueboy-tm/LinuxBacklightManager#3]
python --version
Python 3.9.10

python installer.py 
Start downloading tuxedo keyboard.
-1 / unknown
Start unpack tuxedo keyboard.
Start Compile and install tuxedo keyboard.
Start install Linux Backlight Manager 1.0.1
Traceback (most recent call last):
  File "/usr/src/LinuxBacklightManager/installer.py", line 41, in <module>
    app = os.path.join(getattr(sys, '_MEIPASS'), 'app')
AttributeError: module 'sys' has no attribute '_MEIPASS'

**Comment by blueboy-tm** [comment]
hi
first compile it

**Comment by blueboy-tm** [comment]
check 
https://github.com/blueboy-tm/LinuxBacklightManager#compile-the-code

**Comment by xevilstar** [comment]
/opt/lbm-1.0.1# ./LinuxBacklightManager 
Traceback (most recent call last):
  File "main.py", line 3, in <module>
ModuleNotFoundError: No module named 'qdarktheme'
[114359] Failed to execute script 'main' due to unhandled exception!
  dark theme is installed
